name: PyPi publish workflow

on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.release.target_commitish }}
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10.1'
    - run: pip install poetry
    - run: poetry version ${{ github.event.release.tag_name }}
    - run: poetry publish --build
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
